export const fileActions = {
  NEW_FILE: 'new-file',
  EXISTING_FILE: 'existing-file',
};

export default {
  CREATE_NEW_INVENTORY: 'create-new-inventory',
  INVENTORY_CREATED: 'inventory-created',
  OPEN_EXISTING_INVENTORY: 'open-existing-inventory',
  OPEN_RECENT_INVENTORY: 'open-recent-inventory',
  INVENTORY_OPENED: 'inventory-opened',
  SAVE_INVENTORY: 'save-inventory',
  INVENTORY_SAVED: 'inventory-saved',
  INVENTORY_INITIALIZED: 'inventory-initialized',
  INVENTORY_UPDATED: 'inventory-updated',
  UPDATE_ITEM: 'update-item',
  ADD_NEW_ITEM: 'add-new-item',
  DELETE_ITEM: 'delete-item',
  UPDATE_SETTINGS: 'update-settings',
  UPDATE_FILE_SETTINGS: 'update-file-settings',
  SETTINGS_UPDATED: 'settings-updated',
  INVENTORY_CHANGE_WITHOUT_SAVE: 'inventory-change-without-save',
  UNSAFE_CREATE_NEW_INVENTORY: 'unsafe-create-new-inventory',
  SAVE_AND_CREATE_NEW_INVENTORY: 'save-and-create-new-inventory',
  UNSAFE_OPEN_EXISTING_INVENTORY: 'unsafe-open-existing-inventory',
  SAVE_AND_OPEN_EXISTING_INVENTORY: 'save-and-open-existing-inventory',
  INVALID_FILE_SELECTED: 'invalid-file-selected',
  INVALID_FILE_SELECTED_MIGRATABLE: 'invalid-file-selected-migratable',
  UPGRADE_FILE: 'upgrade-file',
};
